const FETCH_ITEMS = 'FETCH_ITEMS'
const LOAD_ITEMS = 'LOAD_ITEMS'
const TOGGLE_ITEM = 'TOGGLE_ITEM'
const REMOVE_ITEM = 'REMOVE_ITEM'
const ADD_ITEM = 'ADD_ITEM'
const MARK_ALL_AS_UNPACKED = 'MARK_ALL_AS_UNPACKED'
const LOADING = 'LOADING'
const LOADING_SUCCESS = 'LOADING_SUCCESS'
const LOADING_FAILED = 'LOADING_FAILED'

export {
  TOGGLE_ITEM,
  REMOVE_ITEM,
  ADD_ITEM,
  MARK_ALL_AS_UNPACKED,
  FETCH_ITEMS,
  LOAD_ITEMS,
  LOADING,
  LOADING_SUCCESS,
  LOADING_FAILED
}
